### ISSUE TITLE
Project scope and stability

### ISSUE THREAD

**Issue by TedHusted** [valmaev/antforce#1]
From the sample build.xml, it looks like you are adding some interesting tasks to help support continuous integration on Salesforce. 

I'll give the a try over the weekend, but I was just curious as to the project's scope and stability.

Are you planning any other tasks?

Have you tried the similar but different tasks in https://github.com/amguerrero/sfdc_ant_tasks ?

-Ted.
www.dreamops.org

**Comment by valmaev** [comment]
Hello Ted,

Thank you for your interest! 
Please feel free to ask any questions about the project. Suggestions about new tasks/features, bug reports or any feedback are also welcome.

Current features
============
AntForce began as a helper for Force.com Migration Tool that unites useful ideas from different places:

- anonymous Apex from [deployment tools from FinancialForce](https://github.com/financialforcedev/df12-deployment-tools)
- wildcards for tests and JUnit report from [force-deploy-with-xml-report-task](https://code.google.com/archive/p/force-deploy-with-xml-report-task/)
- install/uninstall managed packages via Metadata API from [Enforce](https://github.com/fundacionjala/enforce-gradle-plugin)

But after that I added other features:

- precise code coverage calculations
    - that's a unique ability since Metadata API doesn't return coverage data for classes for which you don't have any unit tests
    - some magic in implementation ( I will cover it in blog post and docs)
- other reports: HTML, Cobertura
- integration with TeamCity
- suite strategies for JUnit reports for better integration with TFS and Visual Studio Team Services

Plans
====
Currently my plan is to cover existing functionality with documentation and write supporting blog posts about the project and CI for Salesforce in general (incl. the right way of managing dependencies for build scripts without storing any .jar-files inside your repo).

**Other plans**

- support ability to exclude some classes from coverage
- fix incorrect HTML rendering in VSTS
- undeploy task 

Stability
======
AntForce follows [Semantic Versioning 2.0](http://semver.org/spec/v2.0.0.html). The current version is `0.9.6` which formally [means](http://semver.org/spec/v2.0.0.html#spec-item-4) that the public API isn't stable yet but I have no plans to introduce breaking changes. But they can be introduced right before `1.0`.

No, I didn't try the tasks from https://github.com/amguerrero/sfdc_ant_tasks, but thanks for the link.

P.S. Sorry for such long-delayed answer. I was on New Year holidays :)
